@DomusNet.API_HostAddress = http://localhost:5242

### Login
POST {{DomusNet.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "correo": "admin@domusnet.com",
  "password": "Admin123!"
}

###
